### ISSUE TITLE
Wooden doors are owned

### ISSUE THREAD

**Issue by tacotexmex** [Yzelast/wood_plus#1]
Using this mod in Minetest Game makes the doors locked. In Minetest Game only steel doors are owned, so these should act as the regular wooden door and not be owned.

**Comment by Yzelast** [comment]
Thanks, i will give a look now. It's cool to see someone still remember this mod,i'm working a lot on my main mod and forgot this one...

**Comment by Yzelast** [comment]
It's fixed now.

**Comment by tacotexmex** [comment]
Awesome, thank you! To me it's strange that not more people use this as it's only logic to have a complete set of doors, ladders etc, when stairs and slabs already come in all wood types. Good work!
